# Generated by Django 5.0.4 on 2024-05-21 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_school', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now=True, verbose_name='Дата оплаты')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма оплаты')),
                ('payment_method', models.CharField(max_length=100, verbose_name='Способ оплаты')),
                ('course_paid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='lms.course', verbose_name='Оплаченный курс')),
                ('lesson_paid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='lms.lesson', verbose_name='Оплаченный урок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ('user', 'payment_date'),
            },
        ),
    ]
