# Generated by Django 5.0.4 on 2024-05-20 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Укажите наименование курса', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='lms.course', verbose_name='Курс'),
        ),
    ]
